### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RhysBower** [racket/handin#31]
What is the license for handin and could we get an explicit LICENSE file added to the repo?

**Comment by LeifAndersen** [comment]
IANAL, and even if I was, I am not your lawyer

I would *guess* its under the same license that the rest of Racket is distributed under.https://download.racket-lang.org/license.html

However, IMO, I honestly don't think it matters, as the code in here is old and broken, and should honestly be rewritten. (Like, the handin server likes to crash under large class sizes.)

**Comment by rfindler** [comment]
I don't think it is clear that rewriting the handin server itself will help with the problem of simultaneously evaluating many programs written in the teaching languages.

**Comment by LeifAndersen** [comment]
I agree with you @rfindler. But from our experience, even if you turn off the evaluation, the handin server still soft-locks and needs to be rebooted fairly frequently. (i.e. every 5 minutes or so during peek use times.)

**Comment by rfindler** [comment]
While I certainly agree that rewriting software is necessary in the general case, it may be easier to try to fix bugs than throw everything away. :)

**Comment by LeifAndersen** [comment]
Maybe. :) Does this package have any active maintainers at the moment?

**Comment by RhysBower** [comment]
Thanks for all of your thoughts. Based on the frequency of the commits it does not appear to be actively maintained which is a shame considering how useful handin is here at UBC.

**Comment by elibarzilay** [comment]
@LeifAndersen -- I'd second @rfindler in this case, I'm guessing that tracking whatever leads to the problems you see is more productive than a complete rewrite.

I am still using it, and have been using it for a very long time; not a class that is as big as fundies, but I do mean a *long* time -- so I should have seen these problems somewhat frequently.  (Currently, I think that I have at most one restart per year.)

Overall, I see something very different than "old and broken".  (Well, "old" but not broken.)

As a side note, one "recent" thing that is relevant if you consider a rewrite is using docker instead, which can isolate anything in a similar way.

**Comment by elibarzilay** [comment]
@RhysBower, IIRC, this code was pulled out of the main repository before the main package split, and that's probably why something like a LICENSE file were not added.  I don't know much about these things since I am also NAL, but not having the file should be considered a bug  because of the above.

**Comment by jackfirth** [comment]
> As a side note, one "recent" thing that is relevant if you consider a rewrite is using docker instead, which can isolate anything in a similar way.

FYI, do not rely on docker alone for running arbitrary untrusted code from students unless you're _really_ sure you know what you're doing. That's not how it's typically meant to be used.

**Comment by elibarzilay** [comment]
@jackfirth, works fine if, indeed, you take care to not use `root` (as so many of them do), which IIRC is the main thing to trip over (since docker is working hard to do it), and even better, use a dedicated user.  Other than that, it's mostly using various features for the needed limitations, and being careful about FS exposure etc.

And in that sense it is actually pretty close to the sandbox library: Racket has all the right knobs, but knowing which ones to pull, how, and in what order is a subtle thing that requires doing so in a library.

But I wasn't seriously suggesting it -- only as a point against rewriting the whole thing.
